########################
# Antigen
########################
source ~/dev/bb/dotfiles/sh/antigen.zsh
source ~/.sh_profile

#antigen bundle StackExchange/blackbox
#antigen bundle brew
#antigen bundle command-not-found
#antigen bundle common-aliases
#antigen bundle docker
#antigen bundle docker-compose
#antigen bundle git
#antigen bundle golang
#antigen bundle npm
#antigen bundle nvm

antigen bundle python
antigen bundle tmux
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
#antigen bundle mafredri/zsh-async
# Select theme.
antigen theme denysdovhan/spaceship-prompt
antigen apply

# the complete options: https://github.com/denysdovhan/spaceship-prompt/blob/master/docs/Options.md
SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  golang        # Go section
  venv          # virtualenv section
  exec_time     # Execution time
  line_sep      # Line break
  vi_mode       # Vi-mode indicator
  exit_code     # Exit code section
  char          # Prompt character
)
SPACESHIP_KUBECONTEXT_SHOW=false
SPACESHIP_PROMPT_SEPARATE_LINE=false
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_GIT_STATUS_SHOW=false
