# load common profile
source ~/.sh_profile
source ~/.oh-my-zsh/lib/history.zsh

zstyle ':completion:*' menu select # select completions with arrow keys
zstyle ':completion:*' group-name '' # group results by category
zstyle ':completion:::::' completer _expand _complete _ignored _approximate # enable approximate matches for completion

########################
# Antigen
########################
source ~/dev/bb/dotfiles/sh/antigen.zsh
#antigen bundle StackExchange/blackbox
#antigen bundle brew
#antigen bundle command-not-found
#antigen bundle common-aliases
#antigen bundle docker
#antigen bundle docker-compose
#antigen bundle git
#antigen bundle golang
#antigen bundle npm
#antigen bundle nvm
antigen bundle history

antigen bundle python
antigen bundle tmux
#antigen bundle osx
#antigen bundle vi-mode

antigen bundle zsh-users/zsh-completions
antigen bundle z
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
#antigen bundle mafredri/zsh-async
# Select theme.
antigen theme denysdovhan/spaceship-prompt
antigen apply

# the complete options: https://github.com/denysdovhan/spaceship-prompt/blob/master/docs/Options.md
SPACESHIP_PROMPT_ORDER=(
  time
  user          # Username section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
#  golang        # Go section
  venv          # virtualenv section
  exec_time     # Execution time
  line_sep      # Line break
  vi_mode       # Vi-mode indicator
  exit_code     # Exit code section
  dir           # Current directory section
  char          # Prompt character
)
SPACESHIP_KUBECONTEXT_SHOW=false
SPACESHIP_PROMPT_SEPARATE_LINE=false
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_DIR_TRUNC=4
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_GIT_STATUS_SHOW=false
SPACESHIP_DIR_PREFIX='['
SPACESHIP_DIR_SUFFIX=']'
PACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_TIME_SHOW=true

eval "$(direnv hook zsh)"
