- hosts: localhost
  gather_facts: ture
  any_errors_fatal: true
  # debugger: on_failed
  tasks:
    - name: install basic tools via brew
      package:
        name:
          - vim
          - watch
          - tmux
          - wget
          - git
          - telnet
          - colordiff
          - bash-completion
          - tree
          - jq
          - zip
          - autossh
          - minikube
          - kubernetes-cli
          - kubectx
          - helm
          - golang
          - the_silver_searcher
          - ripgrep
          - hub
          - mtr
          - pwgen
          - awscli
          - coreutils # include utils such as `grealpath`
          - ncdu # show disk usage
          - gh # github cli
          - java
          - moreutils
          - terraform
          - terragrunt
          - packer
          - libffi  # libffi is a foreign function interface library. It provides a C programming language interface for calling natively compiled functions given information about the target function at run time instead of compile time.
          - fzf # https://github.com/junegunn/fzf. To install useful key bindings and fuzzy completion: $(brew --prefix)/opt/fzf/install
        state: present
      tags:
        - package

    - name: install packages provided via brew cask
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - iterm2
        - visual-studio-code
        - adoptopenjdk8
        - mplayer-osx-extended
        - wireshark
        - adobe-acrobat-reader
        - sublime-text
      tags:
        - package

    - name: Configure git
      delegate_to: localhost
      git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      with_items: "{{ git_config | union(mac_additional_git_config)}}"
      tags:
        - config

    # - name: check whether brew is installed
    #   delegate_to: localhost
    #   shell: which brew
    #   register: brew_installed

    # - name: install brew if not installed
    #   block:
    #     - name: download installation script
    #       shell:
    #     - name: install brew via ruby
    #   when:  brew_installed is failed

    - name: ensure ~/.ssh directory
      file:
        path: ~/.ssh
        state: directory
      tags: ["local"]

    - name: configure ~/.ssh/config
      template:
        src: templates/ssh_config.j2
        dest: "{{ ansible_user_dir }}/.ssh/config"
        mode: 0640
      tags: ["local"]

    - name: install python packages
      pip:
        executable: "{{ ansible_user_dir}}/dev/py3/bin/pip3"
        name:
          - docker-compose
          - ipython
          - ansible
          - flake8
          - jq
          - yq
          - pytest
          - pdfkit
          - pre-commit
          - black
          - pywebcopy # great tool to download web pages
      tags: ["more"]
