########################
# Antigen
########################
source /usr/local/share/antigen/antigen.zsh
source ~/.zsh.theme

antigen bundle StackExchange/blackbox
antigen bundle brew
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle docker
antigen bundle docker-compose
antigen bundle git
antigen bundle golang
antigen bundle npm
antigen bundle nvm
antigen bundle python
antigen bundle tmux
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle mafredri/zsh-async
# Select theme.
antigen theme denysdovhan/spaceship-prompt
# antigen theme bhilburn/powerlevel9k powerlevel9k
antigen apply

